### ISSUE TITLE
Request: https://www.rfc-editor.org/rfc

### ISSUE THREAD

**Issue by martinthomson** [LPardue/edge-tools-ietf#1]
I don't much care about the rest of the site, but the new tools pages link to HTML in this path and so caching would help.

**Comment by LPardue** [comment]
this should be an easy addition under something like `www-rfc-editor-org.lucaspardue.com`

**Comment by LPardue** [comment]
Added in https://github.com/LPardue/edge-tools-ietf/commit/44d6d400a51fc786bdf9e7744786253b2b100cc3, for all resources. Let me know if this addresses your feature request.

**Comment by martinthomson** [comment]
I made one comment about considering `https://rfc-editor.org/` links also.

**Comment by LPardue** [comment]
I think we have a few crossed wires. I've responded to your comment.

**Comment by LPardue** [comment]
Should be fixed now.
